<a href="https://colab.research.google.com/github/kumisganteng/Data-Analytics-Projects/blob/energy_data_ingestion/Energy_Consumption_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Data Ingestion

##1.1 Pemuatan Data

In [14]:
import pandas as pd

AEP_hourly_energy_dataset = "AEP_hourly.csv"
energy_data = pd.read_csv(AEP_hourly_energy_dataset)

##1.2 Inspeksi Awal

In [15]:
energy_data.shape

(121273, 2)

In [16]:
energy_data.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [17]:
energy_data.tail()

                   Datetime   AEP_MW
121268  2018-01-01 20:00:00  21089.0
121269  2018-01-01 21:00:00  20999.0
121270  2018-01-01 22:00:00  20820.0
121271  2018-01-01 23:00:00  20415.0
121272  2018-01-02 00:00:00  19993.0

In [18]:
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121273 entries, 0 to 121272
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  121273 non-null  object
 1   AEP_MW    121273 non-null  float64
dtypes: float64(1), object(1)
memory usage: 1.9+ MB

In [19]:
energy_data.describe()

              AEP_MW
count  121273.000000
mean    15499.513717
std      2591.399065
min      9581.000000
25%     13630.000000
50%     15310.000000
75%     17200.000000
max     25695.000000

###Cek Rentang Waktu

In [20]:
# cek rentang waktu data
print(energy_data['Datetime'].min())
print(energy_data['Datetime'].max())

# cek missing hours
energy_data['Datetime'] = pd.to_datetime(energy_data['Datetime'])
expected = pd.date_range(start=energy_data['Datetime'].min(),
                         end=energy_data['Datetime'].max(),
                         freq='h')
missing_hours = expected.difference(energy_data['Datetime'])
print(f"Missing hours: {len(missing_hours)}")

# cek duplikasi
print(f"Duplikasi: {energy_data.duplicated().sum()}")

# cek missing values
print(energy_data.isnull().sum())

2004-10-01 01:00:00
2018-08-03 00:00:00
Missing hours: 27
Duplikasi: 0
Datetime    0
AEP_MW      0
dtype: int64

In [21]:
energy_data.describe()

                            Datetime         AEP_MW
count                         121273  121273.000000
mean   2011-09-02 03:17:01.553025024   15499.513717
min              2004-10-01 01:00:00    9581.000000
25%              2008-03-17 15:00:00   13630.000000
50%              2011-09-02 04:00:00   15310.000000
75%              2015-02-16 17:00:00   17200.000000
max              2018-08-03 00:00:00   25695.000000
std                              NaN    2591.399065